### PR TITLE
Added Sprites

### PR DESCRIPTION
**Pull request by ExplosBlue**
Added sprite 147: Move while on lift
Added sprite 228: Boo
Added sprite 229: Big Boo

### CODE REVIEW

**Comment by RicBent** [comment]
Those Boos look rather strange. Could you make a boos with opened eyes and then roughly position it where the one with the closed eyes is?

**Comment by ExplosBlue** [comment]
Yeah sure I can do that.

-Update: Changed the sprite images and adjusted the offsets for them.

**Comment by RicBent** [comment]
Doesn't have the boo sprites a bluish flare arround them?
You could use RRWMC's CLIP to make sprite images with semitransparency.

**Comment by ExplosBlue** [comment]
Updated the sprites to contain the blue glow, Used the clip tool to make them semitransparent, Readjusted the height/with settings along with offset values for these new sprite images.

**Comment by ghost** [comment]
The boo one still looks a bit odd.

**Comment by Gota7** [comment]
I have my own sprites I can add, and a new feature called "liquid toggle", which allows the ability to show liquids like lava, water, and poison water. I think someone updated the code though, and how do pull requests work exactly? I'm new to github.

**Pull request merged**
